######  Attributes Supported by Integration Apps #######
# id: Internal Id for the integrations, used by the hooks
# logo: place the image in /public/dashboard/images/integrations and reference here
# i18n_key: the key under which translations for the integration is placed in en.yml
# action: if integration requires external redirect url
# hook_type: ( account / inbox )
# allow_multiple_hooks: whether multiple hooks can be created for the integration
# settings_json_schema: the json schema used to validate the settings hash (https://json-schema.org/)
# settings_form_schema: the formulate schema used in frontend to render settings form (https://vueformulate.com/)
########################################################
captain:
  id: captain
  logo: captain.png
  i18n_key: captain
  action: /captain
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'access_token': { 'type': 'string' },
          'account_id': { 'type': 'string' },
          'account_email': { 'type': 'string' },
          'assistant_id': { 'type': 'string' },
          'inbox_ids': { 'type': 'strings' },
        },
      'required':
        ['access_token', 'account_id', 'account_email', 'assistant_id'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Access Token',
        'type': 'text',
        'name': 'access_token',
        'validation': 'required',
      },
      {
        'label': 'Account ID',
        'type': 'text',
        'name': 'account_id',
        'validation': 'required',
      },
      {
        'label': 'Account Email',
        'type': 'text',
        'name': 'account_email',
        'validation': 'required',
      },
      {
        'label': 'Assistant Id',
        'type': 'text',
        'name': 'assistant_id',
        'validation': 'required',
      },
      {
        'label': 'Inbox Ids',
        'type': 'text',
        'name': 'inbox_ids',
        'validation': '',
      },
    ]
  visible_properties: []
webhooks:
  id: webhook
  logo: webhooks.png
  i18n_key: webhooks
  action: /webhook
  hook_type: account
  allow_multiple_hooks: true
dashboard_apps:
  id: dashboard_apps
  logo: dashboard_apps.png
  i18n_key: dashboard_apps
  hook_type: account
  allow_multiple_hooks: true
openai:
  id: openai
  logo: openai.png
  i18n_key: openai
  action: /openai
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'api_key': { 'type': 'string' },
          'label_suggestion': { 'type': 'boolean' },
        },
      'required': ['api_key'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'API Key',
        'type': 'text',
        'name': 'api_key',
        'validation': 'required',
      },
      {
        'label': 'Show label suggestions',
        'type': 'checkbox',
        'name': 'label_suggestion',
        'validation': '',
      },
    ]
  visible_properties: ['api_key', 'label_suggestion']
linear:
  id: linear
  logo: linear.png
  i18n_key: linear
  action: /linear
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties': { 'api_key': { 'type': 'string' } },
      'required': ['api_key'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'API Key',
        'type': 'text',
        'name': 'api_key',
        'validation': 'required',
      },
    ]
  visible_properties: []
slack:
  id: slack
  logo: slack.png
  i18n_key: slack
  action: https://slack.com/oauth/v2/authorize?scope=commands,chat:write,channels:read,channels:manage,channels:join,groups:read,groups:write,im:write,mpim:write,users:read,users:read.email,chat:write.customize,channels:history,groups:history,mpim:history,im:history,files:read,files:write
  hook_type: account
  allow_multiple_hooks: false
dialogflow:
  id: dialogflow
  logo: dialogflow.png
  i18n_key: dialogflow
  action: /dialogflow
  hook_type: inbox
  allow_multiple_hooks: true
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'project_id': { 'type': 'string' },
          'credentials': { 'type': 'object' },
        },
      'required': ['project_id', 'credentials'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Dialogflow Project ID',
        'type': 'text',
        'name': 'project_id',
        'validation': 'required',
        'validationName': 'Project Id',
      },
      {
        'label': 'Dialogflow Project Key File',
        'type': 'textarea',
        'name': 'credentials',
        'validation': 'required|JSON',
        'validationName': 'Credentials',
        'validation-messages':
          { 'JSON': 'Invalid JSON', 'required': 'Credentials is required' },
      },
    ]
  visible_properties: ['project_id']
google_translate:
  id: google_translate
  logo: google-translate.png
  i18n_key: google_translate
  action: /google_translate
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'project_id': { 'type': 'string' },
          'credentials': { 'type': 'object' },
        },
      'required': ['project_id', 'credentials'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Google Cloud Project ID',
        'type': 'text',
        'name': 'project_id',
        'validation': 'required',
        'validationName': 'Project Id',
      },
      {
        'label': 'Google Cloud Project Key File',
        'type': 'textarea',
        'name': 'credentials',
        'validation': 'required|JSON',
        'validationName': 'Credentials',
        'validation-messages':
          { 'JSON': 'Invalid JSON', 'required': 'Credentials is required' },
      },
    ]
  visible_properties: ['project_id']
dyte:
  id: dyte
  logo: dyte.png
  i18n_key: dyte
  action: /dyte
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'api_key': { 'type': 'string' },
          'organization_id': { 'type': 'string' },
        },
      'required': ['api_key', 'organization_id'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Organization ID',
        'type': 'text',
        'name': 'organization_id',
        'validation': 'required',
      },
      {
        'label': 'API Key',
        'type': 'text',
        'name': 'api_key',
        'validation': 'required',
      },
    ]
  visible_properties: ['organization_id']
shopify:
  id: shopify
  logo: shopify.png
  i18n_key: shopify
  action: /shopify
  hook_type: account
  type: 'ecommerce'
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'url_site': { 'type': 'string' },
          'api_key': { 'type': 'string' },
          'type': { 'type': 'string' },
        },
      'required': ['api_key'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'URL site',
        'type': 'text',
        'name': 'url_site',
        'validation': 'required',
      },
      {
        'label': 'API Key',
        'type': 'text',
        'name': 'api_key',
        'validation': 'required',
      },
      {
        'label': 'Type',
        'type': 'text',
        'name': 'type',
        'validation': 'required',
        'value': 'ecommerce',
        'class': 'hide',
      },
    ]
  visible_properties: ['api_key', 'url_site']
woocommerce:
  id: woo
  logo: woo.png
  i18n_key: woo
  action: /woo
  hook_type: account
  allow_multiple_hooks: false
  type: 'ecommerce'
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'api_key': { 'type': 'string' },
          'label_suggestion': { 'type': 'boolean' },
        },
      'required': ['api_key'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'API Key',
        'type': 'text',
        'name': 'api_key',
        'validation': 'required',
      },
      {
        'label': 'Show label suggestions',
        'type': 'checkbox',
        'name': 'label_suggestion',
        'validation': '',
      },
    ]
  visible_properties: ['api_key', 'label_suggestion']
magento:
  id: magento
  logo: magento.png
  i18n_key: magento
  action: /magento
  hook_type: account
  allow_multiple_hooks: false
  type: 'ecommerce'
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'url_site': { 'type': 'string' },
          'user': { 'type': 'string' },
          'password': { 'type': 'string' },
          'query': { 'type': 'string' },
        },
      'required': ['url_site', 'user', 'password'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'URL site',
        'type': 'text',
        'name': 'url_site',
        'validation': 'required',
      },
      {
        'label': 'User',
        'type': 'text',
        'name': 'user',
        'validation': 'required',
      },
      {
        'label': 'Password',
        'type': 'text',
        'name': 'password',
        'validation': 'required',
      },
      {
        'label': 'Customize product query in GraphQL',
        'type': 'textarea',
        'name': 'query',
        'validation': '',
      },
    ]
  visible_properties: ['api_key', 'user', 'password', 'query']
whatsapp_business:
  id: whatsapp_business
  logo: whatsapp_business.png
  i18n_key: whatsapp_business
  action: /whatsapp_business
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema:
    {
      'type': 'object',
      'properties':
        {
          'number_id': { 'type': 'string' },
          'jwt_token': { 'type': 'string' },
          'accound_id': { 'type': 'string' },
          'version': { 'type': 'string' },
        },
      'required': ['number_id', 'jwt_token', 'accound_id', 'version'],
      'additionalProperties': false,
    }
  settings_form_schema:
    [
      {
        'label': 'Token de acceso',
        'type': 'text',
        'name': 'jwt_token',
        'validation': 'required',
      },
      {
        'label': 'Identificador de número de teléfono',
        'type': 'text',
        'name': 'number_id',
        'validation': 'required',
      },
      {
        'label': 'Identificador de la cuenta de WhatsApp Business',
        'type': 'text',
        'name': 'accound_id',
        'validation': 'required',
      },
      {
        'label': 'Version',
        'type': 'text',
        'name': 'version',
        'validation': 'required',
      },
    ]
  visible_properties: ['jwt_token', 'number_id', 'accound_id', 'version']
